modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"
issueTrackerURL = "${github}/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    authors = "${mod_author}"
    logoFile = "assets/windy/icon.png"

[[dependencies.${mod_id}]]
    modId = "forge"
    type = "required"
    versionRange = "[47,)"
    ordering = "NONE"
    side = "CLIENT"
    mandatory = true

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${mc}"
    ordering = "NONE"
    side = "CLIENT"
    mandatory = true

[[dependencies.${mod_id}]]
    modId = "yet_another_config_lib_v3"
    type = "required"
    versionRange = "[3,)"
    ordering = "NONE"
    side = "CLIENT"
    mandatory = true
